app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sidebarCollapsed = TRUE)
app$setInputs(likes_filter = c(100, 333))
app$setInputs(retweet_filter = c(30, 73))
app$setInputs(retweet_filter = c(56, 73))
app$setInputs(retweet_filter = c(37, 73))
app$setInputs(retweet_filter = c(37, 59))
app$setInputs(likes_filter = c(100, 265))
app$setInputs(slideinput = "2019-11-09")
app$setInputs(slideinput = "2019-11-13")
app$setInputs(retweet_filter = c(37, 74))
app$setInputs(retweet_filter = c(22, 74))
app$setInputs(likes_filter = c(0, 265))
app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
